spring:
    jpa:
        hibernate:
            ddl-auto: ''
    thymeleaf:
        cache: false
    messages:
        cache-seconds: 0
logging:
    level:
        org.hibernate: INFO
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
