truncate table `user`;
truncate table `role`;

insert into `role` (`id`, `name`) values (1, 'ROLE_ADMIN');
insert into `role` (`id`, `name`) values (2, 'ROLE_USER');

-- Value of the `password` is generated by ./gradlew encodePassword -Pargs="test"
-- See build.gradle
insert into `user` (`id`, `username`, `password`, `enabled`, `role_id`, `created_at`, `updated_at`) values (1, 'test', 'c3bf653f3addf1102cecb043a423915aa345b85131e7ea0f84108839415ded416574799c648a1289', true, 1, 0, 0);
insert into `user` (`id`, `username`, `password`, `enabled`, `role_id`, `created_at`, `updated_at`) values (2, 'user1', 'c3bf653f3addf1102cecb043a423915aa345b85131e7ea0f84108839415ded416574799c648a1289', true, 1, 0, 0);
insert into `user` (`id`, `username`, `password`, `enabled`, `role_id`, `created_at`, `updated_at`) values (3, 'user2', 'c3bf653f3addf1102cecb043a423915aa345b85131e7ea0f84108839415ded416574799c648a1289', true, 1, 0, 0);
insert into `user` (`id`, `username`, `password`, `enabled`, `role_id`, `created_at`, `updated_at`) values (4, 'user3', 'c3bf653f3addf1102cecb043a423915aa345b85131e7ea0f84108839415ded416574799c648a1289', true, 1, 0, 0);
insert into `user` (`id`, `username`, `password`, `enabled`, `role_id`, `created_at`, `updated_at`) values (5, 'user4', 'c3bf653f3addf1102cecb043a423915aa345b85131e7ea0f84108839415ded416574799c648a1289', true, 1, 0, 0);
insert into `user` (`id`, `username`, `password`, `enabled`, `role_id`, `created_at`, `updated_at`) values (6, 'user5', 'c3bf653f3addf1102cecb043a423915aa345b85131e7ea0f84108839415ded416574799c648a1289', true, 1, 0, 0);
insert into `user` (`id`, `username`, `password`, `enabled`, `role_id`, `created_at`, `updated_at`) values (7, 'user6', 'c3bf653f3addf1102cecb043a423915aa345b85131e7ea0f84108839415ded416574799c648a1289', true, 1, 0, 0);
insert into `user` (`id`, `username`, `password`, `enabled`, `role_id`, `created_at`, `updated_at`) values (8, 'user7', 'c3bf653f3addf1102cecb043a423915aa345b85131e7ea0f84108839415ded416574799c648a1289', true, 1, 0, 0);
insert into `user` (`id`, `username`, `password`, `enabled`, `role_id`, `created_at`, `updated_at`) values (9, 'user8', 'c3bf653f3addf1102cecb043a423915aa345b85131e7ea0f84108839415ded416574799c648a1289', true, 1, 0, 0);
insert into `user` (`id`, `username`, `password`, `enabled`, `role_id`, `created_at`, `updated_at`) values (10, 'user9', 'c3bf653f3addf1102cecb043a423915aa345b85131e7ea0f84108839415ded416574799c648a1289', true, 1, 0, 0);
insert into `user` (`id`, `username`, `password`, `enabled`, `role_id`, `created_at`, `updated_at`) values (11, 'user10', 'c3bf653f3addf1102cecb043a423915aa345b85131e7ea0f84108839415ded416574799c648a1289', true, 1, 0, 0);
